
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: autopep8
      uses: peter-evans/autopep8@v1.2.0
      
    - name: TODO to Issue
      uses: alstr/todo-to-issue-action@v1.3-beta
